### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by thenextman** [kenh/keychain-pkcs11#15]
What's the license for this project? I couldn't find that information. Thank you!

**Comment by kenh** [comment]
I do not have one, I am not going to give it one for <REASONS>, and I do not understand why people care.

**Comment by irdkwmnsb** [comment]
The reason people care is that having no license forbids anyone to use your software (legally).
This means that no one anywhere cannot contribute, download, run or distribute your software, unless you specify otherwise in your license.
https://www.quora.com/Why-do-open-source-projects-need-a-license

This is important because there are some people and organizations that would want to use your software legally, but are unable to.
If you are unsure what license to use – use MIT.
